name: obsidian_import_pr

# Cron-Trigger: stündlich
on:
  schedule:
    - cron: "*/10 * * * *"  # alle 10min
  push:
    branches:
      - obsidian-import

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Auto Pull Request
          title: your title
          body: Auto-created Pull Request
          branch: ${{ github.ref }} # The branch where you commit
          base: main # Don't forget to
