name: Auto PR from obsidian-import

on:
  push:
    branches:
      - obsidian-import
  schedule:
    - cron: "3 * * * *" # stündlich   ## "*/15 * * * *" # alle 15 Minuten

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if PR already exists
        id: pr-check
        run: |
          PR_NUMBER=$(gh pr list \
            --head obsidian-import \
            --base main \
            --state open \
            --json number \
            --jq '.[0].number')
          
          if [ -n "$PR_NUMBER" ]; then
            echo "Ein offener PR (#$PR_NUMBER) existiert bereits."
            echo "pr_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Kein offener PR gefunden."
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create PR if none exists
        if: steps.pr-check.outputs.pr_exists == 'false'
        run: |
          gh pr create \
            --title "Update from obsidian-import" \
            --body "Automatisch erstellter Pull Request aus obsidian-import." \
            --base main \
            --head obsidian-import
        env:
          GH_TOKEN: ${{ github.token }}
