name: Auto-create PR for obsidian-import branch

on:
  push:
    branches:
      - obsidian-import

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Create PR via GitHub API if none exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="obsidian-import"
          BASE="main"

          # Prüfen, ob ein offener PR existiert
          EXISTING_PR=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REPOSITORY_OWNER}:${BRANCH}&state=open" \
            | jq -r '.[0]?.number // empty')

          if [ -n "$EXISTING_PR" ]; then
            echo "Ein offener PR (#$EXISTING_PR) existiert bereits. Es wird kein neuer erstellt."
          else
            echo "Kein offener PR gefunden. Erstelle neuen PR..."
            PR_DATA=$(jq -n \
              --arg title "Automated blog update $(date +%Y-%m-%d)" \
              --arg head "$BRANCH" \
              --arg base "$BASE" \
              '{title: $title, head: $head, base: $base, maintainer_can_modify: true}')

            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls \
              -d "$PR_DATA"

            echo "PR erstellt."
          fi
