name: Pull Request Action
on:
  push:
    branches:
      - obsidian-import
      
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B main -H obsidian-import --title 'Merge obsidian-import into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
